# Generated by Django 4.0.4 on 2022-11-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('form-builder', 'Form Builder'), ('admin', 'Admin')], default='normal', max_length=25),
        ),
    ]
