# Generated by Django 4.0.4 on 2022-12-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_rename_form_details_form_alter_forms_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elements',
            name='label',
        ),
        migrations.AlterField(
            model_name='elements',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
